Repository DDMers/Deep-Space-13, pull requests merged in 2019-02, with the labels that each got.

#21 Splits items from #18
  DS13/code/game/objects/weapons.dm
  DS13/code/modules/EMH/EMH.dm
  DS13/code/modules/clothing/under/trek.dm
  DS13/code/modules/mob/living/carbon/human/species_types/klingon.dm
  DS13/icons/mob/inhands/weapons/guns_lefthand.dmi
  DS13/icons/mob/inhands/weapons/guns_righthand.dmi
  DS13/icons/mob/inhands/weapons/items_lefthand.dmi
  DS13/icons/mob/inhands/weapons/items_righthand.dmi
  DS13/icons/mob/suit.dmi
  DS13/icons/mob/uniform.dmi
  DS13/icons/obj/clothing/uniforms.dmi
  DS13/icons/obj/suits.dmi
  DS13/icons/weapons/energy.dmi
  DS13/icons/weapons/melee.dmi
  DS13/sound/effects/weapons/phaser.ogg
  DS13/sound/effects/weapons/phaser_adjust.ogg
  DS13/sound/effects/weapons/phaser_hit.ogg
  DS13/sound/effects/weapons/phaser_rifle.ogg
  DS13/sound/effects/weapons/phasercut.ogg
  DeepSpace13.dme
  icons/mob/human_parts_greyscale.dmi
Labels: Feature, Sprites

#24 Atomizes darkmode pr
  code/modules/goonchat/browserassets/css/browserOutput.css
  interface/skin.dmf
Labels: Feature

#23 Adds widescreen mode
  DS13/code/controllers/configuration/entries/game_options.dm
  DS13/code/modules/client/preferences_toggles.dm
  DeepSpace13.dme
  code/__DEFINES/preferences.dm
  code/datums/components/riding.dm
  code/game/mecha/mecha.dm
  code/game/mecha/mecha_actions.dm
  code/game/objects/items/twohanded.dm
  code/game/objects/structures/manned_turret.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/login.dm
  code/modules/power/singularity/emitter.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/misc/beam_rifle.dm
  code/modules/shuttle/navigation_computer.dm
  config/game_options.txt
  config/title_screens/images/default.png
  config/title_screens/images/trek.png
Labels: Config Update, Feature

#25 Fixes KMC PRs getting merged before i can send reviews
  code/modules/admin/verbs/randomverbs.dm
Labels: Fix

#22 Borg gamemode
  DS13/code/modules/borg/antag_datum.dm
  DS13/code/modules/borg/collective.dm
  DS13/code/modules/borg/gamemode.dm
  DS13/code/modules/borg/items+structures.dm
  DS13/code/modules/borg/turfs.dm
  DS13/goonstation/turf_autoalign.dm
  DS13/icons/actions/actions_borg.dmi
  DS13/icons/borg/borg.dmi
  DS13/icons/borg/large_machines.dmi
  DS13/icons/effects/effects.dmi
  DS13/icons/effects/landmarks_static.dmi
  DS13/icons/obj/masks.dmi
  DS13/icons/turf/floors.dmi
  DS13/icons/turf/trek_wall_borg.dmi
  DS13/sound/ambience/ambiborg1.ogg
  DS13/sound/ambience/ambiborg2.ogg
  DS13/sound/ambience/ambiborg3.ogg
  DS13/sound/effects/borg/Head_Assimilated.ogg
  DS13/sound/effects/borg/announce.ogg
  DS13/sound/effects/borg/borg_adapt.ogg
  DS13/sound/effects/borg/borg_adapt2.ogg
  DS13/sound/effects/borg/borg_adapt3.ogg
  DS13/sound/effects/borg/borg_adapt4.ogg
  DS13/sound/effects/borg/borg_transporter.ogg
  DS13/sound/effects/borg/collectivewhisper.ogg
  DS13/sound/effects/borg/dontresist.ogg
  DS13/sound/effects/borg/grab.ogg
  DS13/sound/effects/borg/machines/alcove.ogg
  DS13/sound/effects/borg/machines/borg_adapt.ogg
  DS13/sound/effects/borg/machines/borg_adapt2.ogg
  DS13/sound/effects/borg/machines/borg_adapt3.ogg
  DS13/sound/effects/borg/machines/borg_adapt4.ogg
  DS13/sound/effects/borg/machines/borgforcedoor.ogg
  DS13/sound/effects/borg/machines/borgtransport.ogg
  DS13/sound/effects/borg/machines/convert_table.ogg
  DS13/sound/effects/borg/machines/convert_table2.ogg
  DS13/sound/effects/borg/machines/convertmachine.ogg
  DS13/sound/effects/borg/machines/convertx.ogg
  DS13/sound/effects/borg/progress/10.ogg
  DS13/sound/effects/borg/progress/40.ogg
  DS13/sound/effects/borg/progress/60.ogg
  DS13/sound/effects/borg/progress/70.ogg
  DS13/sound/effects/borg/progress/Victory.ogg
  DS13/sound/effects/borg/progress/borg_theme.ogg
  DS13/sound/effects/borg/resistanceisfutile.ogg
  DS13/sound/effects/borg/whisper-double.ogg
  DS13/sound/effects/borg/whisper-single.ogg
  DS13/sound/effects/borg/withstandassault.ogg
  DeepSpace13.dme
  _maps/map_files/generic/CentCom.dmm
  code/__DEFINES/role_preferences.dm
  code/game/objects/effects/decals/cleanable/humans.dm
  code/game/turfs/simulated/dirtystation.dm
  code/modules/mob/living/living.dm
  config/game_options.txt
  sound/ai/commandreport.ogg
Labels: Config Update, Feature, Map Edit, Needs Review, Needs pictures, Sound

#27 Resprites some common tools+items, map fixes
  DS13/code/game/objects/item_changes.dm
  DS13/code/game/objects/trek_objects.dm
  DS13/goonstation/airlocks.dm
  DS13/goonstation/turf_autoalign.dm
  DS13/icons/obj/card.dmi
  DS13/icons/obj/device.dmi
  DS13/icons/obj/pda.dmi
  DS13/icons/obj/stack_objects.dmi
  DS13/icons/obj/tools.dmi
  DS13/sound/effects/items/laser_scalpel.ogg
  DS13/sound/effects/items/spanner.ogg
  DS13/sound/effects/items/tricorder.ogg
  DS13/sound/effects/items/tricorder_open.ogg
  DeepSpace13.dme
  _maps/map_files/DeepSpace13/DS13-D1.dmm
  _maps/map_files/DeepSpace13/DS13-D2.dmm
  _maps/map_files/DeepSpace13/job_changes.dm
  sound/machines/defib_charge.ogg
  sound/machines/defib_failed.ogg
  sound/machines/defib_ready.ogg
  sound/machines/defib_success.ogg
Labels: Feature, Map Edit, Sound

#30 Fix broken klingon names
  strings/names/klingon.txt
Labels: Feature, Priority

#31 Revert "Atomizes darkmode pr"
  code/modules/goonchat/browserassets/css/browserOutput.css
  interface/skin.dmf
Labels: Revert
