Repository DDMers/Deep-Space-13, pull requests merged in 2019-05, with the labels that each got.

#95 Nerfs the shit out of everything because I fucking died
  DS13/code/game/objects/replicator.dm
  DS13/code/game/objects/weapons.dm
  DS13/code/modules/overmap/combat.dm
  DS13/code/modules/overmap/components.dm
  DS13/code/modules/overmap/events.dm
  DS13/code/modules/overmap/overmap.dm
  DS13/code/modules/overmap/runabout.dm
  DS13/code/modules/overmap/ship_types.dm
  DS13/code/modules/overmap/transporter.dm
  DS13/code/modules/turbolift/turbolift.dm
  DS13/icons/effects/effects.dmi
  DS13/icons/weapons/energy.dmi
  code/datums/components/slippery.dm
  code/modules/jobs/map_changes/DS13_OVERRIDE.dm
  code/modules/research/techweb/all_nodes.dm
  config/jukebox_music/sounds/1812+2466+5.ogg
  config/jukebox_music/sounds/BannedFromArgo+3000+5.ogg
  config/jukebox_music/sounds/bluedanube+2520+5.ogg
  config/jukebox_music/sounds/drunkensailor+2000+5.ogg
Labels: Config Update

#96 EXPERIMENTAL: Attempts to fix naked people
  DS13/code/modules/client/client.dm
  DS13/code/modules/overmap/transporter.dm
  DeepSpace13.dme
Labels: Fix

#99 Exports the round ID to the bot whenever a new round is started
  code/controllers/subsystem/redbot.dm
Labels: Feature
