Repository DDMers/Deep-Space-13, pull requests merged in 2019-03, with the labels that each got.

#33 Adds backstories and job descriptions
  DS13/code/modules/client/preferences.dm
  DS13/icons/previews/command.png
  DS13/icons/previews/engsec.png
  DS13/icons/previews/medsci.png
  DeepSpace13.dme
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/jobs/job_types/captain.dm
  code/modules/jobs/job_types/cargo_service.dm
  code/modules/jobs/job_types/civilian.dm
  code/modules/jobs/job_types/civilian_chaplain.dm
  code/modules/jobs/job_types/engineering.dm
  code/modules/jobs/job_types/job.dm
  code/modules/jobs/job_types/medical.dm
  code/modules/jobs/job_types/science.dm
  code/modules/jobs/job_types/security.dm
  code/modules/jobs/job_types/silicon.dm
Labels: Feature

#34 Adds roundend credits. Roll 'em!
  DS13/code/game/movietitles.dm
  DS13/icons/stars2.gif
  DS13/sound/effects/endcredits.ogg
  DeepSpace13.dme
  code/__HELPERS/roundend.dm
  html/browser/credits.css
Labels: Feature

#36 fixes some of the broken darkmode stuff
  DS13/code/modules/goonchat/darkmode-pref.dm
  code/__DEFINES/preferences.dm
  interface/skin.dmf
Labels: Fix

#39 Adds cadets, vulcans, andorians + new door sprites + morale officer + new circuitboard sprites
  DS13/code/game/airlocks.dm
  DS13/code/game/objects/items/circuitboards/circuitboard.dm
  DS13/code/modules/clothing/under/trek.dm
  DS13/code/modules/jobs/job_types/cadet.dm
  DS13/code/modules/mob/living/carbon/human/species_types/Andorian.dm
  DS13/code/modules/mob/living/carbon/human/species_types/klingon.dm
  DS13/code/modules/mob/living/carbon/human/species_types/vulcan.dm
  DS13/goonstation/airlocks.dm
  DS13/icons/mob/uniform.dmi
  DS13/icons/obj/clothing/uniforms.dmi
  DS13/icons/obj/machinery/doors/command.dmi
  DS13/icons/obj/machinery/doors/security.dmi
  DS13/icons/obj/machinery/doors/standard.dmi
  DS13/icons/obj/module.dmi
  DS13/sound/effects/tng_airlock.ogg
  DeepSpace13.dme
  code/__DEFINES/jobs.dm
  code/modules/jobs/job_types/civilian.dm
  config/game_options.txt
  icons/mob/human_parts_greyscale.dmi
  strings/names/andorian.txt
  strings/names/vulcan.txt
Labels: Config Update, Feature, Sprites

#37 Adds replicators! Simply tell it what you want and it'll make it so.
  DS13/code/game/objects/replicator.dm
  DS13/icons/obj/replicator.dmi
  DS13/icons/obj/replicator_large.dmi
  DS13/sound/effects/replicator-vaporize.ogg
  DS13/sound/effects/replicator.ogg
  DeepSpace13.dme
Labels: Feature

#41 Ports ERIS's hud and adds an LCARS hud
  code/_onclick/hud/hud.dm
  icons/mob/screen_eris.dmi
  icons/mob/screen_lcars.dmi
  icons/mob/screen_lcars_dark.dmi
Labels: Feature, Sprites

#44 Misc
  DS13/code/modules/overmap/ai.dm
  icons/member_content.dmi
Labels: Feature, Sprites

#54 Make it impossible to join as non-mapped jobs
  code/modules/jobs/job_types/civilian.dm
  code/modules/jobs/job_types/civilian_chaplain.dm
  code/modules/jobs/job_types/medical.dm
  code/modules/jobs/job_types/science.dm
  code/modules/jobs/job_types/security.dm
  config/jobs.txt
Labels: Config Update
